theme: jekyll-theme-cayman

author:
  name: 'Sara & Andrey'
  email: sara.andrey@gmail.com
  twitter_username: blabliblup
  facebook_username: blabliblup
  github_username:  blabliblup
  linkedin_username:  blabliblup
